spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=blog;user=sa;password=idjc0915;
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.guolong: info
  file:
    path: log/blog-pro.log
    
    
server:
  port: 8081
    